apiVersion: v1
kind: Pod
metadata:
  name: config-demo
  labels:
    purpose: demo
spec:
  containers:
  - name: config-con
    image: nginx
    env:
    - name: SQLConnectionString
      value: "server=./server;database=demodb;uid=sa;pwd=test"
    - name: MESSAGE
      value: "This is a demo"