apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx1
  name: mynginx1
spec:
  containers:
  - image: nginx
    name: mynginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
