apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app-blue
  template:
    metadata:
      name: nginx-pod
      labels:
        app: app-blue
    spec:
      containers:
      - name: mynginx-con
        image: nginx:1.18.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service-blue
spec:
  type: NodePort
  selector:
    app: app-green
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 8080
    targetPort: 80


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-green
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app-green
  template:
    metadata:
      name: nginx-pod
      labels:
        app: app-green
    spec:
      containers:
      - name: httpd-con
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service-green
spec:
  type: NodePort
  selector:
    app: app-green
  ports:
    - protocol: TCP
      nodePort: 32002
      port: 8080
      targetPort: 80